#!/usr/bin/env bash
set -e

#MISE description="Build uCore image"
#USAGE flag "-i --image <image>" help="Which image to build"
#USAGE flag "-t --tag <tag>" help="Tag to apply to the built image"

echo "Building ${usage_image:-ucore} image..."
podman build \
    --build-arg "IMAGE=${usage_image:-ucore}" \
    --pull=newer \
    --tag "${usage_image:-ucore}:${usage_tag:-stable}" \
    .